package com.elorrieta.primerdia;

public class EjercicioX {

	public static void main(String[] args) {
		// TODO revisar que todos los alumnos hayna borrado los autogenerated
		System.out.println("funciona");
	}

}
