package com.elorrieta.primerdia;

public class EjercicioX {

	public static void main(String[] args) {
		// TODO revisar que todos los alumnos hayna borrado los autogenerated
		System.out.println(4 % 2);

		System.out.println("2 == 2 es " + (2 == 2));
		System.out.println("2 != 2 es " + (2 != 2));
	}

}
